name: GiveMeLeads
options:
  bundleIdPrefix: com.givemeleads
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: true
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
    INFOPLIST_KEY_UIRequiresFullScreen: true
    INFOPLIST_KEY_CFBundleDisplayName: GiveMeLeads
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  GiveMeLeads:
    type: application
    platform: iOS
    sources:
      - path: GiveMeLeads
    dependencies:
      - package: Supabase
        product: Supabase
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2S42RLH67Y
    entitlements:
      path: GiveMeLeads/GiveMeLeads.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default

  GiveMeLeadsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GiveMeLeadsTests
    dependencies:
      - target: GiveMeLeads
